version: '3.8'

services:
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: fastapi-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  backend:
  frontend: